using System;
using UnityEngine;

namespace EarthRecovery
{
    public enum DistrictType { Residential, Commercial, Mixed, Downtown, Suburban }
    public enum BuildingUsage { Residential, Commercial, Office, Public }
    public enum CityRoadKind { MainRoad, SideRoad, Alley }
    public enum LocationType { Shop, Residential, Office, Public, Subway, Street, Alley, Other, SpecialPOI }
    public enum CityTemplatePreset { DenseCommercial, MixedDistrict, ResidentialAlleys, SubwayHub, WideAvenue }

    [Serializable] public struct IntRange
    {
        public int min, max;
        public IntRange(int min, int max) { this.min = min; this.max = max; }
        public int Sample(System.Random rng)
        {
            if (rng == null) throw new ArgumentNullException(nameof(rng));
            if (min > max) throw new ArgumentException("Range min must not exceed max.");
            return (int)(min + (long)Math.Floor(rng.NextDouble() * ((long)max - min + 1)));
        }
    }
    [Serializable] public struct FloatRange
    {
        public float min, max;
        public FloatRange(float min, float max) { this.min = min; this.max = max; }
        public float Sample(System.Random rng)
        {
            if (rng == null) throw new ArgumentNullException(nameof(rng));
            if (!float.IsFinite(min) || !float.IsFinite(max) || min > max) throw new ArgumentException("Invalid finite range.");
            return (float)(min + rng.NextDouble() * ((double)max - min));
        }
    }
    [Serializable] public sealed class MapGenerationRules
    {
        public FloatRange width = new(160, 200), depth = new(160, 200);
    }
    [Serializable] public sealed class RoadGenerationRules
    {
        public IntRange mainRoadCount = new(1, 2), sideRoadCount = new(2, 4), alleyCount = new(1, 3), intersectionCount = new(2, 4);
        public FloatRange width = new(10, 16), blockSize = new(24, 38);
        public float sidewalkWidth = 6;
    }
    [Serializable] public sealed class BuildingGenerationRules
    {
        public FloatRange density = new(.5f, .8f), commercialRatio = new(.3f, .5f), residentialRatio = new(.2f, .4f), officeRatio = new(.1f, .3f), publicRatio = new(.05f, .15f);
    }
    [Serializable] public sealed class POIGenerationRules
    {
        public IntRange shopCount = new(1, 3), subwayEntranceCount = new(0, 1), busStopCount = new(1, 2), publicBuildingCount = new(0, 1);
    }
    [Serializable] public sealed class VehicleGenerationRules { public IntRange parkedCount = new(3, 8); }
    [Serializable] public sealed class PropGenerationRules { public FloatRange density = new(.3f, .6f); }

    [CreateAssetMenu(menuName = "HumanThings/City Layout Template", fileName = "CityLayoutTemplate")]
    public sealed class CityLayoutTemplate : ScriptableObject
    {
        public string templateName = "MixedDistrict";
        [TextArea(3, 8)] public string description;
        [TextArea(3, 10)] public string assetBasis;
        public bool autoGenerated;
        [HideInInspector] public string autoGeneratorId, sourceDatabaseGuid, sourceFingerprint, generatedContentHash;
        public DistrictType districtType = DistrictType.Mixed;
        public MapGenerationRules map = new();
        public RoadGenerationRules roads = new();
        public BuildingGenerationRules buildings = new();
        public POIGenerationRules pois = new();
        public VehicleGenerationRules vehicles = new();
        public PropGenerationRules props = new();

        public void ApplyPreset(CityTemplatePreset preset)
        {
            templateName = preset.ToString(); map = new(); roads = new(); buildings = new(); pois = new(); vehicles = new(); props = new();
            districtType = DistrictType.Mixed;
            switch (preset)
            {
                case CityTemplatePreset.DenseCommercial:
                    districtType = DistrictType.Commercial; buildings.density = new(.8f, 1); buildings.commercialRatio = new(.7f, .9f);
                    buildings.residentialRatio = new(0, 0); pois.shopCount = new(3, 5); roads.mainRoadCount = new(1, 1); break;
                case CityTemplatePreset.ResidentialAlleys:
                    districtType = DistrictType.Residential; roads.mainRoadCount = new(1, 1); roads.alleyCount = new(4, 7);
                    buildings.residentialRatio = new(.7f, .9f); buildings.commercialRatio = new(.05f, .1f); buildings.officeRatio = new(0, 0); break;
                case CityTemplatePreset.SubwayHub:
                    districtType = DistrictType.Downtown; map.width = new(190, 230); map.depth = new(190, 230);
                    roads.sidewalkWidth = 10; pois.subwayEntranceCount = new(2, 3); pois.busStopCount = new(2, 3); break;
                case CityTemplatePreset.WideAvenue:
                    roads.width = new(20, 26); roads.mainRoadCount = new(1, 2); roads.alleyCount = new(0, 1);
                    map.width = new(220, 270); map.depth = new(180, 220); vehicles.parkedCount = new(8, 16); break;
            }
        }
    }
}
