using System;
using System.Collections.Generic;
using System.Linq;
using UnityEngine;

namespace EarthRecovery.Editor
{
    public static class CityTemplateDesigner
    {
        public const string Owner = "HumanThings.AssetMeasuredTemplates.v1";
        static Vector3 FacingSize(HumanThingsAssetEntry e)
        {
            var rotation = HumanThingsPlacementSolver.Rotation(e, Vector3.forward, new System.Random(0), e.category == AssetCategory.Vehicle);
            return rotation.HasValue ? HumanThingsPlacementSolver.RotatedSize(e, rotation.Value) : e.boundsSize;
        }
        public static List<CityLayoutTemplate> Design(CityAssetAnalysis a, List<string> excluded)
        {
            var buildings = Enum.GetValues(typeof(BuildingUsage)).Cast<BuildingUsage>().ToDictionary(u => u, u => CityLayoutAssets.Resolve(a.database, CityLayoutAssets.Building(u)));
            var allBuildings = buildings.Values.SelectMany(v => v).Distinct().ToList();
            var surfaces = a.Query(AssetCategory.Road, PlacementSurface.Ground, "Straight", "Other", "Intersection");
            var walk = a.Query(AssetCategory.Road, PlacementSurface.Ground, "Sidewalk").Where(e => !e.cornerCompatible && Mathf.Min(e.boundsSize.x, e.boundsSize.z) >= 1).ToList();
            if (allBuildings.Count == 0 || surfaces.Count == 0 || walk.Count == 0) throw new InvalidOperationException("Usable buildings, road tiles and sidewalk tiles are required; no templates fabricated.");
            var vehicles = a.Query(AssetCategory.Vehicle, PlacementSurface.Road, "Car", "Van", "Truck", "Bus", "Emergency");
            var subways = a.Query(AssetCategory.Transit, PlacementSurface.Sidewalk, "SubwayEntrance");
            var buses = a.Query(AssetCategory.Transit, PlacementSurface.Sidewalk, "BusStop");
            float unit = CityAssetAnalysis.Percentile(surfaces.Select(e => Mathf.Min(e.boundsSize.x, e.boundsSize.z)), .5f);
            float walkUnit = CityAssetAnalysis.Percentile(walk.Select(e => Mathf.Min(e.boundsSize.x, e.boundsSize.z)), .5f);
            float spacing = 1; // Existing Solver: 0.5m frontage inset + 0.4m containment margin, rounded up.
            float meanWidth = allBuildings.Average(e => FacingSize(e).x), meanDepth = allBuildings.Average(e => FacingSize(e).z);
            float p80 = CityAssetAnalysis.Percentile(allBuildings.Select(e => Mathf.Max(FacingSize(e).x, FacingSize(e).z)), .8f);
            var profiles = new List<string>();
            if (buildings.Values.Count(v => v.Count > 0) >= 2) profiles.Add("CatalogMixed");
            else excluded.Add("CatalogMixed: fewer than two usable building usages.");
            profiles.Add("SparseBlocks");
            if (vehicles.Count >= 2) profiles.Add("WideAvenue");
            else excluded.Add("WideAvenue: insufficient vehicle variety for an avenue profile.");
            if (buildings[BuildingUsage.Commercial].Count >= 3) profiles.Add("MarketBranches"); else excluded.Add("MarketBranches: fewer than 3 usable commercial variants.");
            if (buildings[BuildingUsage.Office].Count >= 3) profiles.Add("OfficeBlocks"); else excluded.Add("OfficeBlocks: fewer than 3 usable office variants.");
            if (subways.Any(e => FacingSize(e).z + spacing <= 12) || buses.Count > 0) profiles.Add("TransitCorridor"); else excluded.Add("TransitCorridor: no transit candidate fits the generator's 12m sidewalk limit.");
            if (buildings[BuildingUsage.Residential].Count == 0) excluded.Add("ResidentialAlleys: no enabled complete residential prefab.");
            if (buildings[BuildingUsage.Public].Count < 3) excluded.Add("PublicDistrict: insufficient public variants.");
            var result = new List<CityLayoutTemplate>();
            foreach (string profile in profiles)
            {
                var t = ScriptableObject.CreateInstance<CityLayoutTemplate>(); t.name = t.templateName = profile;
                t.autoGenerated = true; t.autoGeneratorId = Owner; t.sourceDatabaseGuid = a.databaseGuid; t.sourceFingerprint = a.fingerprint;
                bool sparse = profile == "SparseBlocks", avenue = profile == "WideAvenue", market = profile == "MarketBranches", office = profile == "OfficeBlocks", transit = profile == "TransitCorridor";
                t.districtType = office ? DistrictType.Downtown : market ? DistrictType.Commercial : sparse ? DistrictType.Suburban : DistrictType.Mixed;
                t.roads.sidewalkWidth = Mathf.Clamp(walkUnit + spacing, 2, 12);
                if (transit && subways.Any(e => FacingSize(e).z + spacing <= 12)) t.roads.sidewalkWidth = Mathf.Max(t.roads.sidewalkWidth, subways.Where(e => FacingSize(e).z + spacing <= 12).Min(e => FacingSize(e).z) + spacing);
                float laneEnvelope = vehicles.Count == 0 ? unit : CityAssetAnalysis.Percentile(vehicles.Select(e => FacingSize(e).x), .9f) + 1.4f;
                float roadWidth = Mathf.Max(unit * (avenue ? 3 : 2), laneEnvelope * 2);
                t.roads.width = new(Mathf.Clamp(roadWidth, 6, 30), Mathf.Clamp(roadWidth + unit * .5f, 6, 30));
                // blockSize currently controls lot frontage, not the entire multi-building block.
                float lotUnit = Mathf.Max(p80 + spacing * 2, meanWidth + meanDepth * .5f + spacing * 2);
                float targetLotsPerSide = sparse ? 3 : market ? 5 : 4;
                t.roads.blockSize = new(Mathf.Clamp(lotUnit * (market ? .9f : 1), 16, 65), Mathf.Clamp(lotUnit * (avenue || office ? 1.35f : 1.15f), 16, 70));
                float crossSection = (p80 + t.roads.sidewalkWidth + spacing) * 2 + t.roads.width.max;
                float mapSize = Mathf.Max(crossSection * (avenue ? 3 : 2), (t.roads.blockSize.max + spacing) * targetLotsPerSide + t.roads.width.max + 2 * t.roads.sidewalkWidth);
                t.map.width = new(Mathf.Clamp(mapSize, 100, 450), Mathf.Clamp(mapSize + lotUnit, 100, 500));
                t.map.depth = new(Mathf.Clamp(mapSize * (sparse ? .9f : 1), 100, 450), Mathf.Clamp(mapSize + lotUnit * (office ? 1.5f : 1), 100, 500));
                int sideCapacity = Mathf.Clamp(Mathf.FloorToInt(t.map.width.min / (p80 * 2 + t.roads.sidewalkWidth * 2 + t.roads.width.max)), 1, 5);
                t.roads.mainRoadCount = new(1, avenue || office ? 2 : 1);
                t.roads.sideRoadCount = new(sparse ? 1 : Mathf.Max(1, sideCapacity - 1), sparse ? 2 : sideCapacity);
                t.roads.alleyCount = new(sparse || avenue || transit ? 0 : 1, sparse || avenue ? 0 : market ? sideCapacity + 1 : 2);
                t.roads.intersectionCount = new(sparse ? 0 : 1, Mathf.Max(1, sideCapacity));
                float areaRatio = meanWidth * meanDepth / ((meanWidth + spacing * 2) * (meanDepth + spacing * 2));
                float density = Mathf.Clamp01(areaRatio * (sparse ? .6f : market ? 1.1f : .9f));
                t.buildings.density = new(density * .9f, Mathf.Min(1, density * 1.1f));
                float Weight(BuildingUsage u) => buildings[u].Count * (u == BuildingUsage.Commercial && market || u == BuildingUsage.Office && office ? 2 : 1);
                float sum = buildings.Keys.Sum(Weight);
                FloatRange Ratio(BuildingUsage u) { float r = Weight(u) / sum; return new(r * .95f, r * 1.05f); }
                t.buildings.commercialRatio = Ratio(BuildingUsage.Commercial); t.buildings.residentialRatio = Ratio(BuildingUsage.Residential);
                t.buildings.officeRatio = Ratio(BuildingUsage.Office); t.buildings.publicRatio = Ratio(BuildingUsage.Public);
                t.pois.shopCount = new(0, market ? Mathf.Min(2, buildings[BuildingUsage.Commercial].Count / 4) : 0);
                t.pois.publicBuildingCount = new(0, 0);
                t.pois.subwayEntranceCount = new(transit && subways.Any(e => FacingSize(e).z + spacing <= t.roads.sidewalkWidth) ? 1 : 0, transit && subways.Any(e => FacingSize(e).z + spacing <= t.roads.sidewalkWidth) ? 1 : 0);
                t.pois.busStopCount = new(transit && buses.Count > 0 ? 1 : 0, buses.Count > 0 ? transit ? 2 : 1 : 0);
                float carLength = vehicles.Count == 0 ? 1 : CityAssetAnalysis.Percentile(vehicles.Select(e => FacingSize(e).z), .9f) + 2;
                int parking = vehicles.Count == 0 ? 0 : Mathf.Min(60, Mathf.FloorToInt(t.map.width.min / carLength * (sparse ? .1f : avenue ? .35f : .2f)));
                t.vehicles.parkedCount = new(parking / 2, parking);
                int propVariants = new[] { "Lamp", "Sign", "Trash", "Bench", "TrafficLight" }.Sum(s => a.Query(AssetCategory.StreetProp, PlacementSurface.Sidewalk, s).Count);
                float propDensity = propVariants == 0 ? 0 : Mathf.Clamp01((float)propVariants / (propVariants + allBuildings.Count) * (market ? 1 : sparse ? .3f : .65f));
                t.props.density = new(propDensity * .8f, propDensity);
                t.description = profile + ": " + (office ? "office-weighted blocks and parallel main roads" : market ? "shop-weighted branching streets and more alleys" : transit ? "transit stops with a footprint-sized sidewalk" : avenue ? "wider measured road modules, larger lots, more parking" : sparse ? "fewer branches, low occupancy and traffic" : "library-proportional mixed business district");
                t.assetBasis = $"Usable buildings={allBuildings.Count}; mean facing footprint={meanWidth:F3} x {meanDepth:F3}m; P80 side={p80:F3}m; road module={unit:F3}m; sidewalk module={walkUnit:F3}m. Ratios use usable subtype counts, not total fragments. Lengths derive from these measurements; profile multipliers are documented design policies, not inferred asset facts.";
                result.Add(t);
            }
            return result;
        }

        public static CityTemplateValidation Tune(CityLayoutTemplate t, HumanThingsAssetDatabase db)
        {
            var adjustments = new List<string>(); CityTemplateValidation r = null;
            for (int round = 0; round < 4; round++)
            {
                r = CityTemplateValidation.Run(t, db); r.tuningRounds = round;
                if (r.passed) break;
                if (round == 3) break;
                if (r.buildings.Rate < .8f)
                {
                    t.map.width = Grow(t.map.width, 1.2f, 500); t.map.depth = Grow(t.map.depth, 1.2f, 500);
                    t.roads.blockSize = Grow(t.roads.blockSize, 1.15f, 70);
                    adjustments.Add("Building rate " + r.buildings.Rate.ToString("P1") + ": map x1.2 and frontage x1.15 (bounded by generator limits).");
                }
                if (r.vehicles.Rate < .8f)
                {
                    t.vehicles.parkedCount = new(Mathf.Max(1, t.vehicles.parkedCount.min - 1), Mathf.Max(1, t.vehicles.parkedCount.max - 1));
                    adjustments.Add("Vehicle target reduced after measured placement shortfall; nonzero demand retained.");
                }
                if (r.props.Rate < .8f) { t.props.density = new(t.props.density.min * .7f, t.props.density.max * .7f); adjustments.Add("Prop density x0.7 after measured placement shortfall."); }
                if (r.requiredPOIs.Rate < .95f)
                {
                    t.pois.shopCount = Reduce(t.pois.shopCount); t.pois.busStopCount = new(t.pois.busStopCount.min, Mathf.Max(t.pois.busStopCount.min, t.pois.busStopCount.max - 1));
                    adjustments.Add("Optional shop/extra stop range narrowed. Core transit minimum retained.");
                }
            }
            var holdout = CityTemplateValidation.Run(t, db, 10, true);
            holdout.seeds.InsertRange(0, r.seeds); holdout.buildings.Add(r.buildings); holdout.vehicles.Add(r.vehicles); holdout.props.Add(r.props); holdout.requiredPOIs.Add(r.requiredPOIs);
            holdout.passed &= r.passed; holdout.tuningRounds = r.tuningRounds; holdout.adjustments = adjustments;
            return holdout;
        }
        static FloatRange Grow(FloatRange r, float scale, float max) => new(Mathf.Min(max, r.min * scale), Mathf.Min(max, r.max * scale));
        static IntRange Reduce(IntRange r) => new(Mathf.Max(0, r.min - 1), Mathf.Max(0, r.max - 1));
    }
}
