using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace EarthRecovery.Editor
{
    [Serializable] public sealed class CityTemplateSnapshot { public string name, path, values; }
    [Serializable] public sealed class CityTemplateBuildReport
    {
        public CityAssetAnalysis analysis;
        public List<CityTemplateValidation> validations = new();
        public List<CityTemplateSnapshot> templates = new();
        public List<string> excluded = new(), notes = new();
    }
    public static class CityTemplateAutoBuilder
    {
        public const string DefaultFolder = "Assets/CityGeneration/AutoTemplates";
        public static string ContentHash(CityLayoutTemplate template)
        {
            var copy = UnityEngine.Object.Instantiate(template); copy.name = template.name; copy.generatedContentHash = "";
            try { return CityAssetAnalysis.Hash(JsonUtility.ToJson(copy)); }
            finally { UnityEngine.Object.DestroyImmediate(copy); }
        }
        public static bool Owned(CityLayoutTemplate t, string guid) => t != null && t.autoGenerated && t.autoGeneratorId == CityTemplateDesigner.Owner && t.sourceDatabaseGuid == guid;
        public static bool Unmodified(CityLayoutTemplate t) => !string.IsNullOrEmpty(t.generatedContentHash) && ContentHash(t) == t.generatedContentHash;
        public static CityTemplateBuildReport Build(HumanThingsAssetDatabase db, string folder = DefaultFolder, bool rebuild = false, Func<float, string, bool> cancel = null, bool exportReport = true)
        {
            ValidateFolder(folder);
            var report = new CityTemplateBuildReport { analysis = CityAssetAnalysis.Analyze(db) };
            if (string.IsNullOrEmpty(report.analysis.databaseGuid)) throw new ArgumentException("Save the source database as a project asset before building templates.");
            var candidates = CityTemplateDesigner.Design(report.analysis, report.excluded);
            try
            {
                // Complete all dry runs before committing any persistent template changes.
                for (int i = 0; i < candidates.Count; i++)
                {
                    if (cancel?.Invoke(i / (float)candidates.Count, candidates[i].templateName) == true) throw new OperationCanceledException("Template build canceled; assets unchanged.");
                    var validation = CityTemplateDesigner.Tune(candidates[i], db); report.validations.Add(validation);
                    if (!validation.passed) report.excluded.Add(candidates[i].templateName + ": failed training/holdout thresholds; no asset created.");
                }
                EnsureFolder(folder);
                var retained = new HashSet<string>();
                for (int i = 0; i < candidates.Count; i++)
                {
                    var t = candidates[i]; var validation = report.validations[i]; if (!validation.passed) continue;
                    string path = folder + "/" + t.templateName + ".asset";
                    var existing = AssetDatabase.LoadAssetAtPath<CityLayoutTemplate>(path);
                    if (AssetDatabase.LoadMainAssetAtPath(path) != null)
                    {
                        if (!Owned(existing, report.analysis.databaseGuid) || !Unmodified(existing))
                        { report.notes.Add(path + ": user-owned/edited asset preserved; generated copy uses a unique path."); path = AssetDatabase.GenerateUniqueAssetPath(path); existing = null; }
                        else if (!rebuild)
                        { report.notes.Add(path + ": existing auto asset preserved; use Rebuild All to update."); retained.Add(path); continue; }
                    }
                    t.assetBasis += "\nValidation: 10 tuning + 10 independent holdout seeds. Buildings " + validation.buildings + "; vehicles " + validation.vehicles + "; props " + validation.props + "; POIs " + validation.requiredPOIs;
                    t.generatedContentHash = ContentHash(t);
                    if (existing == null) { var saved = UnityEngine.Object.Instantiate(t); saved.name = t.name; AssetDatabase.CreateAsset(saved, path); }
                    else { Undo.RecordObject(existing, "Rebuild measured template"); EditorUtility.CopySerialized(t, existing); EditorUtility.SetDirty(existing); }
                    retained.Add(path); validation.templatePath = path;
                    report.templates.Add(new CityTemplateSnapshot { name = t.templateName, path = path, values = JsonUtility.ToJson(t, true) });
                }
                if (rebuild)
                    foreach (var guid in AssetDatabase.FindAssets("t:CityLayoutTemplate", new[] { folder }))
                    {
                        string path = AssetDatabase.GUIDToAssetPath(guid); if (retained.Contains(path)) continue;
                        var t = AssetDatabase.LoadAssetAtPath<CityLayoutTemplate>(path);
                        if (Owned(t, report.analysis.databaseGuid) && Unmodified(t))
                        { AssetDatabase.DeleteAsset(path); report.notes.Add("Removed obsolete generated template: " + path); }
                    }
                AssetDatabase.SaveAssets();
                if (report.validations.Count(v => v.passed) < 4) report.notes.Add("Fewer than four profiles passed. No unsupported/low-success templates fabricated.");
                if (exportReport) Export(report); return report;
            }
            finally { foreach (var t in candidates) UnityEngine.Object.DestroyImmediate(t); }
        }
        public static CityTemplateBuildReport Validate(HumanThingsAssetDatabase db, string folder = DefaultFolder)
        {
            ValidateFolder(folder);
            var r = new CityTemplateBuildReport { analysis = CityAssetAnalysis.Analyze(db) };
            if (!AssetDatabase.IsValidFolder(folder)) return r;
            foreach (string guid in AssetDatabase.FindAssets("t:CityLayoutTemplate", new[] { folder }))
            {
                string path = AssetDatabase.GUIDToAssetPath(guid); var t = AssetDatabase.LoadAssetAtPath<CityLayoutTemplate>(path);
                var v = CityTemplateValidation.Run(t, db, 10, true); v.templatePath = path; r.validations.Add(v);
                r.templates.Add(new CityTemplateSnapshot { name = t.templateName, path = path, values = JsonUtility.ToJson(t, true) });
                if (t.sourceFingerprint != r.analysis.fingerprint) r.notes.Add(path + ": database changed; validation uses the current database.");
            }
            Export(r, "Revalidation"); return r;
        }
        static void ValidateFolder(string folder)
        {
            if (string.IsNullOrWhiteSpace(folder) || !folder.StartsWith("Assets/", StringComparison.Ordinal) || folder.Contains("..") || folder.Contains('\\') || folder.Split('/').Any(string.IsNullOrWhiteSpace))
                throw new ArgumentException("Choose a project folder under Assets.");
            if (AssetDatabase.LoadMainAssetAtPath(folder) != null && !AssetDatabase.IsValidFolder(folder))
                throw new ArgumentException("The output must be a folder, not a file.");
        }
        static void EnsureFolder(string folder)
        {
            if (AssetDatabase.IsValidFolder(folder)) return;
            int slash = folder.LastIndexOf('/'); string parent = folder.Substring(0, slash);
            if (parent != "Assets") EnsureFolder(parent);
            AssetDatabase.CreateFolder(parent, folder.Substring(slash + 1));
        }
        public static void Export(CityTemplateBuildReport r, string name = "Build")
        {
            const string folder = "Docs/MeasuredCityTemplates"; Directory.CreateDirectory(folder);
            File.WriteAllText(folder + "/" + name + ".json", JsonUtility.ToJson(r, true));
            var b = new StringBuilder("# Asset-Measured Templates\n\n");
            b.AppendLine("Registered prefabs: " + r.analysis.total + ". Usable here means metadata-eligible, not a guarantee of generator selection or spatial fit. Unknowns are not generated. No database entries overwritten.\n");
            b.AppendLine("| Category | Registered | Usable | Mean footprint (usable) | Mean bounds (usable) |\n|---|---:|---:|---|---|");
            foreach (var c in r.analysis.categories) b.AppendLine($"| {c.category} | {c.total} | {c.usable} | {c.usableSizes.meanFootprint:F3} | {c.usableSizes.meanBounds:F3} |");
            b.AppendLine("\n## Subcategories\n");
            foreach (var c in r.analysis.categories) b.AppendLine(c.category + ": " + string.Join(", ", c.subCategories.Select(s => s.name + "=" + s.total + "/" + s.usable)) + " (registered/usable)\n");
            b.AppendLine("\n## Actual Generator Candidates\n");
            foreach (var c in r.analysis.generatorCandidates) b.AppendLine("- " + c.name + ": " + c.usable);
            b.AppendLine("\n## Validation\n\n| Template | Seeds | Buildings | Vehicles | StreetProps | Required POIs | Empty lots | Overlaps | Passed |\n|---|---:|---|---|---|---|---|---:|---|");
            foreach (var v in r.validations)
            {
                int lots = v.seeds.Sum(s => s.lots), empty = v.seeds.Sum(s => s.emptyLots);
                b.AppendLine($"| {v.templateName} | {v.seeds.Count} | {v.buildings} | {v.vehicles} | {v.props} | {v.requiredPOIs} | {empty}/{lots} | {v.seeds.Sum(s => s.overlapPairs)} | {v.passed} |");
            }
            foreach (var v in r.validations) b.AppendLine("\n" + v.templateName + " tuning: " + string.Join("; ", v.adjustments));
            b.AppendLine("\n## Template Values\n");
            foreach (var t in r.templates) b.AppendLine(t.path + "\n" + new string((char)96, 3) + "json\n" + t.values + "\n" + new string((char)96, 3) + "\n");
            b.AppendLine("\n## Exclusions and Warnings\n");
            foreach (string warning in r.excluded.Concat(r.notes).Concat(r.analysis.warnings)) b.AppendLine("- " + warning);
            b.AppendLine("\n## Unknown Names\n"); foreach (var n in r.analysis.unknownNames) b.AppendLine("- " + n);
            b.AppendLine("\n## All Road Bounds\n\n| Prefab | Subcategory | Bounds | Footprint | Enabled |\n|---|---|---|---|---|");
            foreach (var e in r.analysis.entries.Where(e => e.category == AssetCategory.Road)) b.AppendLine($"| {e.displayName} | {e.subCategory} | {e.boundsSize:F4} | {e.footprintWidth:F4} x {e.footprintDepth:F4} | {e.placementEnabled} |");
            File.WriteAllText(folder + "/" + name + ".md", b.ToString());
        }
        public static void BatchBuild()
        {
            if (!Application.isBatchMode) throw new InvalidOperationException("Batch mode only.");
            var report = Build(AssetDatabase.LoadAssetAtPath<HumanThingsAssetDatabase>("Assets/CityGeneration/CityAssetDatabase.asset"), rebuild: true);
            Debug.Log("MEASURED_TEMPLATES templates=" + report.templates.Count + "\n" + string.Join("\n", report.validations.Select(v => v.templateName + " passed=" + v.passed + " buildings=" + v.buildings + " props=" + v.props + " POI=" + v.requiredPOIs)));
        }
    }
}
